### ISSUE TITLE
IR_VerMAIN_FMW sensor MQTT Topic parse error

### ISSUE THREAD

**Issue by kattantak** [gracingpro/blauberg-homeassistant#2]
Hello,

I have integrated this into Home Assistant 2023.6.3 and running smoothly.
Just complaining about this IR_VerMAIN_FMW sensor.

As far as I understood HA cannot parse the MQTT topic because icon need to define other way.   

Could you please check this?

Thank you in advance.

Br,
Mike

-------------------------------------------------------------------------------
2023-07-05 11:09:29.063 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'name': 'IR_VerMAIN_FMW', 'enabled_by_default': True, 'unique_id': 'Blauberg_IR_VerMAIN_FMW', 'state_topic': 'Blauberg/IR_VerMAIN_FMW/state', 'json_attributes_topic': 'Blauberg/IR_VerMAIN_FMW/state', 'value_template': '{{ value_json.value }}', 'device': {'identifiers': ['Blauberg'], 'name': 'Blauberg', 'model': 'Blauberg', 'manufacturer': 'Blauberg'}, 'icon': 'mdi-update', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 270, in async_discover
    config: DiscoveryInfoType = discovery_schema(discovery_payload)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
        ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: Icons should be specified in the form "prefix:name" for dictionary value @ data['icon']

**Comment by gracingpro** [comment]
Hello Mike,

I hope this message finds you well. I'm pleased to report that the issue you reported has been addressed and fixed in our latest release, version 1.0.4. We appreciate your patience and feedback as we worked on resolving this problem.

Please make sure to update your software to this latest release. You can update to the latest version using the command `sudo docker compose pull && sudo docker compose up -d`

If you encounter any difficulties or if this problem persists after updating, please don't hesitate to let us know. Feel free to reopen this issue or create a new one.

Thanks again for your contribution to the improvement of our project.

Best regards,
Dmitry

**Comment by kattantak** [comment]
Hello,

Error log is disappeared and IR_VerMAIN_FMW sensor appeared in HA.

Thanks for the very quick fix.
 
Br,
Mike
